# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-14 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TBDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='部门名称')),
                ('leader', models.CharField(blank=True, max_length=100, verbose_name='领导')),
                ('path', models.CharField(blank=True, max_length=100, verbose_name='路径')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='human.TBDepartment', verbose_name='上级部门')),
            ],
        ),
        migrations.CreateModel(
            name='TBEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='员工姓名')),
                ('no', models.CharField(blank=True, max_length=100, verbose_name='工号')),
                ('gen', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='手机号')),
                ('head', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=200, verbose_name='工牌照')),
                ('duty', models.CharField(blank=True, max_length=100, verbose_name='职务')),
                ('nation', models.CharField(blank=True, max_length=30, verbose_name='民族')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('nickname', models.CharField(blank=True, max_length=200, verbose_name='个性签名')),
                ('qq', models.CharField(blank=True, max_length=50, verbose_name='QQ')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human.TBDepartment', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
        ),
    ]
