# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh', models.CharField(max_length=200, verbose_name='中文名')),
                ('en', models.CharField(blank=True, max_length=200, verbose_name='英文名')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '在线'), (2, '下线')], default=0, verbose_name='状态')),
                ('cover', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=200, verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='ip')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('code', models.IntegerField(choices=[(1, '打开'), (2, '关闭')], verbose_name='编码')),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh', models.CharField(max_length=200, verbose_name='中文名')),
                ('en', models.CharField(blank=True, max_length=200, verbose_name='英文名')),
                ('colors', models.TextField(blank=True, verbose_name='颜色盘')),
                ('kind', models.IntegerField(choices=[(0, '纯色'), (1, '过渡色')], default=0, verbose_name='颜色种类')),
            ],
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(blank=True, max_length=300, verbose_name='标签')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '在线'), (2, '下线')], default=0, verbose_name='状态')),
                ('url', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=200, verbose_name='图片')),
                ('color_block', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=200, verbose_name='色块')),
                ('thumbnail', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=200, verbose_name='缩略图')),
                ('uploadtime', models.DateTimeField(blank=True, null=True, verbose_name='上传日期')),
                ('resolution', models.CharField(blank=True, max_length=30, verbose_name='分辨率')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='大小')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='WechatShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='ip')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.SourceImage', verbose_name='图片')),
            ],
        ),
        migrations.AddField(
            model_name='imagereport',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.SourceImage', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='images',
            field=models.ManyToManyField(to='color.SourceImage', verbose_name='图片'),
        ),
    ]
